basePath: /
definitions:
  person.PersonCreateRequest:
    properties:
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
  person.PersonResponse:
    properties:
      age:
        type: integer
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
  person.PersonUpdateRequest:
    properties:
      age:
        type: integer
      gender:
        type: string
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API для управления людьми с обогащением данных
  title: People API
  version: "1.0"
paths:
  /person:
    get:
      description: Возвращает всех людей из БД
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/person.PersonResponse'
            type: array
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Получить список людей
      tags:
      - people
    post:
      consumes:
      - application/json
      description: Добавляет человека в БД с обогащением данных (возраст, пол, национальность)
      parameters:
      - description: Данные человека
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/person.PersonCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/person.PersonResponse'
        "400":
          description: Неверный JSON
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Создать новую запись о человеке
      tags:
      - people
  /person/{id}:
    delete:
      description: Удаляет запись о человеке из БД
      parameters:
      - description: ID человека
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Неверный ID
          schema:
            type: string
        "404":
          description: Человек не найден
          schema:
            type: string
      summary: Удалить человека
      tags:
      - people
    get:
      description: Возвращает данные конкретного человека
      parameters:
      - description: ID человека
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/person.PersonResponse'
        "400":
          description: Неверный ID
          schema:
            type: string
        "404":
          description: Человек не найден
          schema:
            type: string
      summary: Получить человека по ID
      tags:
      - people
    patch:
      consumes:
      - application/json
      description: Изменяет данные человека (частичное обновление)
      parameters:
      - description: ID человека
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/person.PersonUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/person.PersonResponse'
        "400":
          description: Неверный запрос
          schema:
            type: string
        "404":
          description: Человек не найден
          schema:
            type: string
      summary: Обновить данные человека
      tags:
      - people
swagger: "2.0"
